CREATE TABLE RESERVA_ASIENTO
(
	ID              INTEGER         NOT NULL,
	ASIENTO     	VARCHAR2(3) 	NOT NULL,
	TIQUETE_ID      INTEGER     	NOT NULL,
    CONSTRAINT PK_RESERVA_ASIENTO PRIMARY KEY (ID),
    CONSTRAINT FK_RESERVA_ASIENTO_TIQUETE FOREIGN KEY (TIQUETE_ID) REFERENCES TIQUETE(ID),
    CONSTRAINT UQ_ASIENTO_POR_TIQUETE UNIQUE (TIQUETE_ID, ASIENTO)
);
