CREATE TABLE CLIENTE
(
    DNI          NUMBER(12)     NOT NULL,
    NOMBRE       VARCHAR2(100),
    APELLIDO     VARCHAR2(100),
    ES_VIP          CHAR(1),
    EMAIL           VARCHAR2(100),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI)
);
