CREATE TABLE PELICULA
(
    ID          INTEGER         NOT NULL,
    TITULO       VARCHAR2(100)   NOT NULL,
    PRODUCTORA       VARCHAR2(50),
    FECHA_ESTRENO    DATE       NOT NULL,
    FUNCION_MANANA   VARCHAR2(20),
    FUNCION_TARDE   VARCHAR2(20),
    FUNCION_NOCHE    VARCHAR2(20),
    TEATRO_ID    INTEGER        NOT NULL,
    CONSTRAINT PK_PELICULA PRIMARY KEY (ID),
    CONSTRAINT FK_PELICULA_TEATRO FOREIGN KEY (TEATRO_ID) REFERENCES TEATRO(ID)
);
