CREATE SEQUENCE SEQ_PELICULA_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TIQUETE_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RESERVA_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_FUNCION_CARTELERA_ID START WITH 1 INCREMENT BY 1 NOCACHE;
