CREATE VIEW VW_RESERVAS_CINE AS
SELECT
    C.NOMBRE || ' ' || C.APELLIDO AS CLIENTE,
    P.TITULO AS PELICULA,
    T.HORARIO_FUNCION,
    T.ESTADO,
    T.PRECIO,
    R.ASIENTO
FROM TIQUETE T
JOIN CLIENTE C ON T.CLIENTE_DNI = C.DNI
JOIN PELICULA P ON T.PELICULA_ID = P.ID
JOIN RESERVA_ASIENTO R ON R.TIQUETE_ID = T.ID;
