CREATE TABLE TEATRO (
    ID      INTEGER        NOT NULL,
    NOMBRE  VARCHAR2(100)   NOT NULL,
    LUGAR   VARCHAR2(100)   NOT NULL,
    CAPACIDAD_ASIENTOS NUMBER(3)   NOT NULL,
    CONSTRAINT PK_TEATRO PRIMARY KEY (ID)
) TABLESPACE CINE_TBS;

ALTER TABLE TEATRO ADD CIUDAD VARCHAR2(100);
