CREATE TABLE PELICULA
(
    ID               INTEGER         NOT NULL,
    TITULO           VARCHAR2(100)   NOT NULL,
    TITULO_ORIGINAL           VARCHAR2(100)   NOT NULL,
    PRODUCTORA       VARCHAR2(100)     NOT NULL,
    FECHA_ESTRENO    DATE            NOT NULL,
    SINOPSIS         VARCHAR2(500)   NOT NULL, 
    CONSTRAINT PK_PELICULA PRIMARY KEY (ID),
) TABLESPACE CINE_TBS;
