CREATE TABLE TIQUETE
(
    ID            INTEGER          NOT NULL,
    CANTIDAD_ASIENTOS NUMBER(3)    NOT NULL,
    HORARIO_FUNCION   VARCHAR2(20) NOT NULL,
    PRECIO        NUMBER(7,2)      NOT NULL,
    FECHA_COMPRA  DATE             DEFAULT SYSDATE,
    ESTADO VARCHAR2(20) DEFAULT 'PAGADO'
        CHECK (ESTADO IN ('PAGADO', 'RESERVADO', 'CANCELADO')),
    FUNCION_ID    INTEGER          NOT NULL,
    CLIENTE_DNI   NUMBER(12)       NOT NULL,
    CONSTRAINT PK_TIQUETE PRIMARY KEY (ID),
    CONSTRAINT FK_TIQUETE_FUNCION FOREIGN KEY (FUNCION_ID) REFERENCES FUNCION_CARTELERA(ID),
    CONSTRAINT FK_TIQUETE_CLIENTE FOREIGN KEY (CLIENTE_DNI) REFERENCES CLIENTE(DNI)
) TABLESPACE CINE_TBS;
