CREATE TABLE FUNCION_CARTELERA (
    ID              INTEGER         NOT NULL,
    PELICULA_ID     INTEGER         NOT NULL,
    TEATRO_ID       INTEGER         NOT NULL,
    FUNCION_MANANA  VARCHAR2(20),
    FUNCION_TARDE   VARCHAR2(20),
    FUNCION_NOCHE   VARCHAR2(20),
    EN_CARTELERA    CHAR(1) DEFAULT 'S' CHECK (EN_CARTELERA IN ('S','N')),
    CONSTRAINT PK_FUNCION_CARTELERA PRIMARY KEY (ID),
    CONSTRAINT FK_FUNCION_CARTELERA_PELICULA_ FOREIGN KEY (PELICULA_ID) REFERENCES PELICULA(ID),
    CONSTRAINT FK_FUNCION_CARTELERA_TEATRO FOREIGN KEY (TEATRO_ID) REFERENCES TEATRO(ID)
) TABLESPACE CINE_TBS;
